#!/usr/bin/env python

import mapzen.pelias
import mapzen.geojson.markdown
import logging
import optparse
import sys
import pprint

if __name__ == '__main__':

    parser = optparse.OptionParser()

    parser.add_option('--lat', dest='latitude', action='store', help='The latitude you are trying to reverse geocode')
    parser.add_option('--lon', dest='longitude', action='store', help='The latitude you are trying to reverse geocode')
    parser.add_option('-r', '--raw', dest='raw', action='store_true', default=False, help='Return raw unparse GeoJSON (default is false)')
    parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='be chatty (default is false)')

    options, args = parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)
	
    method = 'reverse'
    
    query = " ".join(args)

    params = {'lat': options.latitude, 'lon': options.longitude}

    api = mapzen.pelias.api()
    rsp = api.execute_method(method, params, raw=options.raw)

    mapzen.geojson.markdown.convert(rsp)
    sys.exit()
